# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ #(modulesPath + "/installer/scan/not-detected.nix")
      (modulesPath + "/profiles/qemu-guest.nix") # Virtmanager test
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  # boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "virtio_pci" "sr_mod" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "virtio_blk" ];
  # boot.initrd.kernelModules = [ "z3fold" "crc32c-intel" "lz4hc" "lz4hc_compress" "sd_mod" "zram" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Test with #### - ZFS - ##### 
  # fileSystems."/" =
  #   { device = "NIXOS/root";
  #     fsType = "zfs";
  #   };

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-label/GRUB";
  #     fsType = "vfat";
  #   };
  
  # fileSystems."/home" =
  #   { device = "NIXOS/home";
  #     fsType = "zfs";
  #   };

  ### BTRFS ###
  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXOS";
      fsType = "btrfs";
      options = [ "subvol=@" "rw""noatime" "ssd" "compress-force=zstd:15" "space_cache=v2" "commit=120" "autodefrag" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/NIXOS";
      fsType = "btrfs";
      options = [ "subvol=@home" "rw" "noatime" "ssd" "compress-force=zstd:15" "space_cache=v2" "commit=120" "autodefrag" "discard=async" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-label/NIXOS";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "rw""noatime" "ssd" "compress-force=zstd:15" "space_cache=v2" "commit=120" "autodefrag" "discard=async" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-label/NIXOS";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-label/NIXOS";
      fsType = "btrfs";
      options = [ "subvol=@tmp" "rw""noatime" "ssd" "compress-force=zstd:15" "space_cache=v2" "commit=120" "autodefrag" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/NIXOS";
      fsType = "btrfs";
      options = [ "subvol=@nix" "rw""noatime" "ssd" "compress-force=zstd:15" "space_cache=v2" "commit=120" "autodefrag" "discard=async" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-label/GRUB";
      fsType = "vfat";
      options = [ "rw" "defaults" "noatime" "nodiratime" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    # nvidia = {
    ##  package = "config.boot.kernelPackages.nvidiaPackages.legacy_340"; ## oldmac
    #   modesetting.enable = true;
    #   prime = {
    #       intelBusId = "PCI:0:2:0";
    #       nvidiaBusId = "PCI:1:0:0";
    #       sync.enable = true;
    #       offload = {
    #           enable = true;
    #           enableOffloadCmd = true;
    #        };
    #   };
    #   nvidiaPersistenced = true;
    #   powerManagement.enable = true;
    # };
    # opengl = {
    #   extraPackages = [ intel-media-driver intel-ocl vaapiIntel intel-gpu-tools ];
    #   driSupport = true;
    #   driSupport32Bit = true;
    # };
  };
  # virtualisation.podman.enableNvidia = true;
}
